apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi-controller
  namespace: argocd
spec:
  destination:
    namespace: sample-app
    server: https://kubernetes.default.svc
  project: sample-project
  source:
    path: unifi-controller/
    repoURL: https://github.com/dominikfe/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
