kind: Service
apiVersion: v1
metadata:
  name: lb-unpoller
spec:
  ports:
    - name: '8081'
      protocol: TCP
      port: 8081
      targetPort: 37288
  selector:
    name: unifi-poller
  type: LoadBalancer
  loadBalancerIP: 192.168.1.33
---
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-unpoller
spec:
  storageClassName: "nfs" # same storage class as pvc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.5 # ip addres of nfs server
    path: "/nfs/unpoller" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-unpoller
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 8Gi